countryCodesForSmsVerificationexport const countryCodesForSmsVerification = [
    { code: 'AF', name: 'Afghanistan', dial_code: '+93', priority: 0, areaCodes: null },
    { code: 'AL', name: 'Albania', dial_code: '+355', priority: 0, areaCodes: null },
    { code: 'DZ', name: 'Algeria', dial_code: '+213', priority: 0, areaCodes: null },
    { code: 'AS', name: 'AmericanSamoa', dial_code: '+1684', priority: 0, areaCodes: null },
    { code: 'AD', name: 'Andorra', dial_code: '+376', priority: 0, areaCodes: null },
    { code: 'AO', name: 'Angola', dial_code: '+244', priority: 0, areaCodes: null },
    { code: 'AI', name: 'Anguilla', dial_code: '+1264', priority: 0, areaCodes: null },
    { code: 'AQ', name: 'Antarctica', dial_code: '+672', priority: 0, areaCodes: null },
    { code: 'AG', name: 'Antigua and Barbuda', dial_code: '+1268', priority: 0, areaCodes: null },
    { code: 'AR', name: 'Argentina', dial_code: '+54', priority: 0, areaCodes: null },
    { code: 'AM', name: 'Armenia', dial_code: '+374', priority: 0, areaCodes: null },
    { code: 'AW', name: 'Aruba', dial_code: '+297', priority: 0, areaCodes: null },
    { code: 'AU', name: 'Australia', dial_code: '+61', priority: 0, areaCodes: null },
    { code: 'AT', name: 'Austria', dial_code: '+43', priority: 0, areaCodes: null },
    { code: 'AZ', name: 'Azerbaijan', dial_code: '+994', priority: 0, areaCodes: null },
    { code: 'BS', name: 'Bahamas', dial_code: '+1242', priority: 0, areaCodes: null },
    { code: 'BH', name: 'Bahrain', dial_code: '+973', priority: 0, areaCodes: null },
    { code: 'BD', name: 'Bangladesh', dial_code: '+880', priority: 0, areaCodes: null },
    { code: 'BB', name: 'Barbados', dial_code: '+1246', priority: 0, areaCodes: null },
    { code: 'BY', name: 'Belarus', dial_code: '+375', priority: 0, areaCodes: null },
    { code: 'BE', name: 'Belgium', dial_code: '+32', priority: 0, areaCodes: null },
    { code: 'BZ', name: 'Belize', dial_code: '+501', priority: 0, areaCodes: null },
    { code: 'BJ', name: 'Benin', dial_code: '+229', priority: 0, areaCodes: null },
    { code: 'BM', name: 'Bermuda', dial_code: '+1441', priority: 0, areaCodes: null },
    { code: 'BT', name: 'Bhutan', dial_code: '+975', priority: 0, areaCodes: null },
    { code: 'BO', name: 'Bolivia', dial_code: '+591', priority: 0, areaCodes: null },
    { code: 'BA', name: 'Bosnia and Herzegovina', dial_code: '+387', priority: 0, areaCodes: null },
    { code: 'BW', name: 'Botswana', dial_code: '+267', priority: 0, areaCodes: null },
    { code: 'BR', name: 'Brazil', dial_code: '+55', priority: 0, areaCodes: null },
    { code: 'IO', name: 'British Indian Ocean Territory', dial_code: '+246', priority: 0, areaCodes: null },
    { code: 'BN', name: 'Brunei Darussalam', dial_code: '+673', priority: 0, areaCodes: null },
    { code: 'BG', name: 'Bulgaria', dial_code: '+359', priority: 0, areaCodes: null },
    { code: 'BF', name: 'Burkina Faso', dial_code: '+226', priority: 0, areaCodes: null },
    { code: 'BI', name: 'Burundi', dial_code: '+257', priority: 0, areaCodes: null },
    { code: 'KH', name: 'Cambodia', dial_code: '+855', priority: 0, areaCodes: null },
    { code: 'CM', name: 'Cameroon', dial_code: '+237', priority: 0, areaCodes: null },
    { code: 'CA', name: 'Canada', dial_code: '+1', priority: 0, areaCodes: null },
    { code: 'CV', name: 'Cape Verde', dial_code: '+238', priority: 0, areaCodes: null },
    { code: 'KY', name: 'Cayman Islands', dial_code: '+ 345', priority: 0, areaCodes: null },
    { code: 'CF', name: 'Central African Republic', dial_code: '+236', priority: 0, areaCodes: null },
    { code: 'TD', name: 'Chad', dial_code: '+235', priority: 0, areaCodes: null },
    { code: 'CL', name: 'Chile', dial_code: '+56', priority: 0, areaCodes: null },
    { code: 'CN', name: 'China', dial_code: '+86', priority: 0, areaCodes: null },
    { code: 'CO', name: 'Colombia', dial_code: '+57', priority: 0, areaCodes: null },
    { code: 'KM', name: 'Comoros', dial_code: '+269', priority: 0, areaCodes: null },
    { code: 'CG', name: 'Congo', dial_code: '+242', priority: 0, areaCodes: null },
    { code: 'CK', name: 'Cook Islands', dial_code: '+682', priority: 0, areaCodes: null },
    { code: 'CR', name: 'Costa Rica', dial_code: '+506', priority: 0, areaCodes: null },
    { code: 'HR', name: 'Croatia', dial_code: '+385', priority: 0, areaCodes: null },
    { code: 'CU', name: 'Cuba', dial_code: '+53', priority: 0, areaCodes: null },
    { code: 'CY', name: 'Cyprus', dial_code: '+357', priority: 0, areaCodes: null },
    { code: 'CZ', name: 'Czech Republic', dial_code: '+420', priority: 0, areaCodes: null },
    { code: 'CD', name: 'Democratic Republic of the Congo', dial_code: '+243', priority: 0, areaCodes: null },
    { code: 'DK', name: 'Denmark', dial_code: '+45', priority: 0, areaCodes: null },
    { code: 'DJ', name: 'Djibouti', dial_code: '+253', priority: 0, areaCodes: null },
    { code: 'DM', name: 'Dominica', dial_code: '+1767', priority: 0, areaCodes: null },
    { code: 'DO', name: 'Dominican Republic', dial_code: '+1849', priority: 0, areaCodes: null },
    { code: 'EC', name: 'Ecuador', dial_code: '+593', priority: 0, areaCodes: null },
    { code: 'EG', name: 'Egypt', dial_code: '+20', priority: 0, areaCodes: null },
    { code: 'SV', name: 'El Salvador', dial_code: '+503', priority: 0, areaCodes: null },
    { code: 'GQ', name: 'Equatorial Guinea', dial_code: '+240', priority: 0, areaCodes: null },
    { code: 'ER', name: 'Eritrea', dial_code: '+291', priority: 0, areaCodes: null },
    { code: 'EE', name: 'Estonia', dial_code: '+372', priority: 0, areaCodes: null },
    { code: 'ET', name: 'Ethiopia', dial_code: '+251', priority: 0, areaCodes: null },
    { code: 'FK', name: 'Falkland Islands (Malvinas)', dial_code: '+500', priority: 0, areaCodes: null },
    { code: 'FO', name: 'Faroe Islands', dial_code: '+298', priority: 0, areaCodes: null },
    { code: 'FJ', name: 'Fiji', dial_code: '+679', priority: 0, areaCodes: null },
    { code: 'FI', name: 'Finland', dial_code: '+358', priority: 0, areaCodes: null },
    { code: 'FR', name: 'France', dial_code: '+33', priority: 0, areaCodes: null },
    { code: 'GF', name: 'French Guiana', dial_code: '+594', priority: 0, areaCodes: null },
    { code: 'PF', name: 'French Polynesia', dial_code: '+689', priority: 0, areaCodes: null },
    { code: 'GA', name: 'Gabon', dial_code: '+241', priority: 0, areaCodes: null },
    { code: 'GM', name: 'Gambia', dial_code: '+220', priority: 0, areaCodes: null },
    { code: 'GE', name: 'Georgia', dial_code: '+995', priority: 0, areaCodes: null },
    { code: 'DE', name: 'Germany', dial_code: '+49', priority: 0, areaCodes: null },
    { code: 'GH', name: 'Ghana', dial_code: '+233', priority: 0, areaCodes: null },
    { code: 'GI', name: 'Gibraltar', dial_code: '+350', priority: 0, areaCodes: null },
    { code: 'GR', name: 'Greece', dial_code: '+30', priority: 0, areaCodes: null },
    { code: 'GL', name: 'Greenland', dial_code: '+299', priority: 0, areaCodes: null },
    { code: 'GD', name: 'Grenada', dial_code: '+1473', priority: 0, areaCodes: null },
    { code: 'GP', name: 'Guadeloupe', dial_code: '+590', priority: 0, areaCodes: null },
    { code: 'GU', name: 'Guam', dial_code: '+1671', priority: 0, areaCodes: null },
    { code: 'GT', name: 'Guatemala', dial_code: '+502', priority: 0, areaCodes: null },
    { code: 'GN', name: 'Guinea', dial_code: '+224', priority: 0, areaCodes: null },
    { code: 'GW', name: 'Guinea-Bissau', dial_code: '+245', priority: 0, areaCodes: null },
    { code: 'GY', name: 'Guyana', dial_code: '+592', priority: 0, areaCodes: null },
    { code: 'HT', name: 'Haiti', dial_code: '+509', priority: 0, areaCodes: null },
    { code: 'HN', name: 'Honduras', dial_code: '+504', priority: 0, areaCodes: null },
    { code: 'HK', name: 'Hong Kong', dial_code: '+852', priority: 0, areaCodes: null },
    { code: 'HU', name: 'Hungary', dial_code: '+36', priority: 0, areaCodes: null },
    { code: 'IS', name: 'Iceland', dial_code: '+354', priority: 0, areaCodes: null },
    { code: 'IN', name: 'India', dial_code: '+91', priority: 0, areaCodes: null },
    { code: 'ID', name: 'Indonesia', dial_code: '+62', priority: 0, areaCodes: null },
    { code: 'IQ', name: 'Iraq', dial_code: '+964', priority: 0, areaCodes: null },
    { code: 'IE', name: 'Ireland', dial_code: '+353', priority: 0, areaCodes: null },
]
